openapi: 3.1.0
info:
  title: Ariventures Authentication
  description: Ariventures Authentication
  version: 1.0.0
servers:
  - url: 'https://ariventures-data.vercel.app'
  - url: 'http://localhost:4000'
paths:
  /users/login:

  
