openapi: 3.1.0
info:
  title: Ariventures Authentication
  description: Ariventures Authentication
  version: 1.0.0
servers:
  - url: 'https://ariventures-data.vercel.app'
  - url: 'http://localhost:4000'
paths:
  /users/signup:
    post:
      summary: Sign Up user via Supaabse Auth
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User
          content:
            application/json:
              schema:
                type: object
  /users/profile/{userId}:
    get:
      summary: Get User profile from user supabase UUID
      parameters:
        - name: userId
          in: path
          required: true
          description: UUID of user
          schema:
            type: string
      responses:
        200:
          description: user profile
  