swagger: "2.0"
info:
  title: Countries
  description: Countries API for Ariventures
  version: 1.0.0
host: ariventures-data.vercel.app
schemes:
  - https
paths:
  /countries:
    get:
      description: Get all countries
      responses:
        200:
          description: New response

  
